#!/usr/bin/env bash
# RAR 2.0 AUDIO-mode fixtures (GH #6): deterministic PCM-like content that
# RAR 2.90's -mm heuristic genuinely routes into its audio model.
#
# WHY THESE EXIST
#   The audio coefficient adaptation was fabricated (per-sample sign
#   correlation, +/-32 clamps) where the reference adapts every 32 samples via
#   an 11-bucket accumulator with [-17,16] clamps — AND the audio alphabet
#   constant was wrong (MC20=257, not the LZ alphabet's 298), so the audio
#   table read consumed 894 code lengths instead of 771 and desynchronised at
#   the first audio block. The committed `rar2_v20_mm` fixture is text, which
#   RAR 2.x never routes into audio mode, so 18 unit tests validated the
#   fabrication against itself. These fixtures make the audio path load-bearing:
#   at the broken state, all of them read "unrar OK, rarz INVALID".
#
#   The generated bytes are sine-derived and deterministic; awk's %c emits
#   UTF-8 for values >= 128, which is FINE — what matters is that RAR 2.90
#   classified the result as audio (verified at generation time by the
#   red/green history, and continuously by the corpus gate).
#
# ONE-TIME, OFF-LINE; committed; NOT byte-reproducible (mtimes).
# Usage:  nix develop -c bash tests/generate_rar2_audio_fixtures.sh
set -u
FIXTURES="tests/fixtures"
RAR290_URL="https://www.rarlab.com/rar/wrar290.exe"
die() { echo "ERROR: $*" >&2; exit 1; }
[ -d "$FIXTURES" ] || die "run from the repo root"
command -v wine >/dev/null 2>&1 || die "wine required"
command -v unrar >/dev/null 2>&1 || die "unrar required (nix develop -c)"

work=$(mktemp -d); trap 'rm -rf "$work"' EXIT
curl -sS -o "$work/wrar290.exe" "$RAR290_URL" || die "download failed"
unrar x -o+ "$work/wrar290.exe" Rar.exe "$work/" >/dev/null 2>&1 || die "no Rar.exe"

awk 'BEGIN{for(i=0;i<200000;i++){v=int(128+100*sin(i/23)+8*sin(i/711));printf "%c",v%256}}' > "$work/mono.pcm"
awk 'BEGIN{for(i=0;i<100000;i++){l=int(128+90*sin(i/31));r=int(128+90*sin(i/29+1));printf "%c%c",l%256,r%256}}' > "$work/stereo.pcm"

gen() { # gen <output> <input>
	local out="$FIXTURES/$1" in="$2"
	rm -f "$out"
	( cd "$work" && WINEDEBUG=-all wine Rar.exe a -inul -mm -m5 "$1" "$in" ) >/dev/null 2>&1
	[ -f "$work/$1" ] || die "RAR 2.90 produced no $1"
	mv "$work/$1" "$out"
	unrar t "$out" >/dev/null 2>&1 || die "$out failed unrar verification"
	echo "  wrote $out ($(wc -c < "$out") bytes)"
}
gen rar2_v20_audio_mono.rar   mono.pcm
gen rar2_v20_audio_stereo.rar stereo.pcm
echo "RAR 2.0 audio fixtures generated."
